name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: karitham
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/karitham/gol:${{ github.ref_name }}
          cache-from: type=registry,ref=ghcr.io/karitham/gol
          cache-to: type=inline
