name: push

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      KRAUD_CERT: ${{ secrets.KRAUD_CERT }}
      KRAUD_KEY: ${{ secrets.KRAUD_KEY }}
      KRAUD_CA: ${{ secrets.KRAUD_CA }}
      KRAUD_FEED: ${{ secrets.KRAUD_FEED }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Put certs in files
        run: |
          echo "$KRAUD_CERT" > cert.pem
          echo "$KRAUD_KEY" > key.pem
          echo "$KRAUD_CA" > ca.crt

      - name: Push to your kraudcloud store
        run: |
          curl --key key.pem \
            --cert cert.pem \
            --cacert ca.crt \
            "https://k8s.m.kraudcloud.com/apis/kraudcloud.com/v1/feeds/$KRAUD_FEED/app" \
            -H "Content-Type: application/yaml" \
            -X PUT --data-binary @golinks.yaml
